---
shell: 
  auto:
    exec: /usr/local/bin/bash
    flag:
      interactive: [ --rcfile, __GOSH_INIT__, __GOSH_ARGS__ ]
      commandline: [ -c, __GOSH_ARGS__ ]

profile:
  auto:
    cwd: __PWD__
    env: []
    inherit: []
    include:
      - defines.bash
      - host.bash
      - paths.bash
      - git/paths.bash
      - go/paths.bash
      - perl/paths.bash
      - python/paths.bash
      - poetry/paths.bash
      - restic/paths.bash
      - ripgrep/paths.bash
      - rust/paths.bash
      - java/paths.bash
      - openocd/paths.bash
      - hub/paths.bash
      - bat/paths.bash
      - hugo/paths.bash
      - duc/paths.bash
      - mutt/paths.bash
      - pgp/paths.bash
      - trace32/paths.bash
      - wireshark/paths.bash
      - sigrok/paths.bash
      - colors.bash
      - functions.bash
      - openocd/functions.bash
      - hub/functions.bash
      - duc/functions.bash
      - restic/functions.bash
      - trace32/functions.bash
      - pio/functions.bash
      - ripgrep/functions.bash
      - aliases.bash
      - hub/aliases.bash
      - bat/aliases.bash
      - python/aliases.bash
      - go/aliases.bash
      - ripgrep/aliases.bash
      - prompt.bash
      - git/prompt.bash
      - completion.bash
      - arduino-cli/completion.bash
      - mbed/completion.bash
      - fd/completion.bash
      - gh/completion.bash
      - git/completion.bash
      - hub/completion.bash
      - hugo/completion.bash
      - go/completion.bash
      - go/golangci-lint/completion.bash
      - poetry/completion.bash
      - restic/completion.bash
      - ripgrep/completion.bash
      - rust/completion.bash
      - task/completion.bash
      - tmux/completion.bash
      - terminal.bash
      - gh/terminal.bash
      - git/terminal.bash
      - pgp/terminal.bash
  arduino:
    cwd: __PWD__
    env: []
    inherit: []
    include:
      - arduino-cli.bash
  segger:
    cwd: __PWD__
    env: []
    inherit: []
    include:
      - functions.bash
  openocd:    
    cwd: __PWD__
    env: []
    inherit: []
    include:
      - functions.bash
  tinygo:
    cwd: __PWD__
    env: []
    inherit: []
    include:
      - paths.bash
      - functions.bash
      - aliases.bash
      - completion.bash

