---
shell: /bin/bash
args: [ --rcfile, __GOSH_INIT__, __GOSH_ARGS__ ]
cmdflag: -c
env:
  - auto:
    - host.bash
    - go/paths.bash
    - rust/paths.bash
    - paths.bash
    - colors.bash
    - functions.bash
    - aliases.bash
    - git/prompt.bash
    - prompt.bash
    - git/completion.bash
    - go/completion.bash
    - rust/completion.bash
    - completion.bash
    - terminal.bash
  - arduino:
    - arduino-cli.bash
  - segger:
    - segger-jlink.bash
